### Get all todos
GET http://localhost:5077/todos

### Get todo by id
GET http://localhost:5077/todos/1

### Get Task
GET http://localhost:5077/tasks/

### Create a new todo
POST http://localhost:5077/todos
Content-Type: application/json

{
  "id": 1,
  "name": "Learn ASP.NET Core",
  "dueDate": "2025-10-10T00:00:00",
  "isCompleted": false
}

### Create another todo
POST http://localhost:5077/todos
Content-Type: application/json

{
  "id": 2,
  "name": "Build a Web API",
  "dueDate": "2025-10-15T00:00:00",
  "isCompleted": false
}


### Delete todo by id
DELETE http://localhost:5077/todos/1

### Get todos
GET http://localhost:5077/todos